---
name: Linux Build

on:
  push:
    branches: ['main', 'dev']
    tags: ['v*']
  pull_request:
    branches: ['dev']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: '6.4.2'
        host: 'ubuntu'
        target: 'desktop'
        arch: 'gcc_64'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential fakeroot devscripts lintian

    - name: Build project
      run: |
        mkdir build
        cd build
        qmake6 ..
        make -j $(nproc)

    - name: Create deb package
      run: |
        mkdir -p build/deb/usr/local/bin
        cp build/your_executable build/deb/usr/local/bin/
        mkdir -p build/deb/DEBIAN
        echo "Package: openterfaceqt
        Version: ${GITHUB_REF#refs/tags/}
        Section: base
        Priority: optional
        Architecture: all
        Depends: libqt6core6 (>= 6.4.2), libqt6multimedia6 (>= 6.4.2), libqt6serialport6 (>= 6.4.2)
        Maintainer: TechXArtisan <info@techxartisan.com>
        Description: OpenterfaceQT" > build/deb/DEBIAN/control
        dpkg-deb --build build/deb

    - name: Rename and move deb package for upload
      run: mv build/deb.deb build/openterfaceqt_${GITHUB_REF#refs/tags/}.deb

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: deb-package
        path: build/openterfaceqt_${GITHUB_REF#refs/tags/}.deb